/**
 * EndNote "Cite While You Write" (CWYW) compatible Word field generation.
 *
 * Round 11 — the Word export must produce references that EndNote can manage
 * directly: when the user opens the .docx in Word with the EndNote add-in
 * active, every in-text citation is recognized as an EndNote citation and the
 * bibliography is recognized as the EndNote reference list. Adding or deleting
 * a citation in EndNote then renumbers everything automatically ("Update
 * Citations and Bibliography"). The embedded per-citation records also form a
 * "traveling library" that can be imported into the user's EndNote library.
 *
 * The field structure mirrors what EndNote itself writes (verified against a
 * hardened open-source converter that emits the identical compound layout):
 *
 *   <w:r><w:fldChar w:fldCharType="begin" w:dirty="true"/></w:r>
 *   <w:r><w:instrText xml:space="preserve"> ADDIN EN.CITE </w:instrText></w:r>
 *   <w:r><w:fldChar w:fldCharType="begin" w:dirty="true">
 *          <w:fldData xml:space="preserve">BASE64(EndNote XML)</w:fldData>
 *        </w:fldChar></w:r>
 *   <w:r><w:instrText xml:space="preserve"> ADDIN EN.CITE.DATA </w:instrText></w:r>
 *   <w:r><w:fldChar w:fldCharType="end"/></w:r>
 *   <w:r><w:fldChar w:fldCharType="separate"/></w:r>
 *   …visible citation result runs (e.g. superscript "[1]")…
 *   <w:r><w:fldChar w:fldCharType="end"/></w:r>
 *
 * The bibliography is wrapped in an unnumbered ADDIN EN.REFLIST field whose
 * result is the visible reference list paragraphs:
 *
 *   begin → instrText " ADDIN EN.REFLIST " → separate → [list] → end
 *
 * All injection happens as post-processing on the packed document.xml (the
 * `docx` library cannot express compound fields), using unique text tokens as
 * anchors. Everything is string-level but the anchors are generated by us and
 * guaranteed unique, and the result is validated (fldChar begin/end balance)
 * before it is returned.
 */
import { createHash } from "node:crypto";

/** One EndNote record (journal-article shaped), keyed by citation number. */
export interface EndNoteRecord {
  /** Citation number ([n] → n). Also used as the EndNote RecNumber. */
  n: number;
  /** Individual author strings ("Jumper J", "Evans R", …). */
  authors: string[];
  title: string;
  journal?: string;
  year?: string;
  doi?: string;
  /** PubMed ID — emitted as an EndNote accession-num. */
  pmid?: string;
  url?: string;
}

/**
 * Parse the numbers referenced by an inline citation marker such as "[1]",
 * "[1,2]" or "[3-5]" (en-dash accepted) into an explicit number list.
 */
export function parseCitationNumbers(marker: string): number[] {
  const inner = marker.replace(/^\[/, "").replace(/\]$/, "");
  return inner
    .split(/[,\s]+/)
    .flatMap((s) => {
      const rm = s.match(/^(\d{1,3})[-–](\d{1,3})$/);
      if (rm) {
        const arr: number[] = [];
        for (let n = parseInt(rm[1], 10); n <= parseInt(rm[2], 10); n++) arr.push(n);
        return arr;
      }
      const n = parseInt(s, 10);
      return isNaN(n) ? [] : [n];
    })
    .filter((n) => n >= 1);
}

export interface ParsedRefLine {
  authors: string;
  year?: string;
  journal?: string;
  title: string;
  url?: string;
}

/**
 * Parse one "[n] Authors (Year), Journal. Title. — URL" reference line (the
 * v2 compose format — the single source of truth for the body's numbering)
 * into structured fields. Unlike the audit-oriented parser in
 * citation-audit.ts, this accepts commas inside journal names ("Journal of
 * the Royal Society, Interface") and strips the trailing URL after the
 * em-dash separator. Anything it cannot recognize degrades gracefully: the
 * whole body becomes the title.
 */
export function parseRefLineForRecord(line: string): ParsedRefLine | null {
  const m = line.match(/^\s*\[\d+\]\s*(.+)$/);
  if (!m) return null;
  const body = m[1].trim();

  // Split off the trailing URL (compose format: "… — https://…").
  let main = body;
  let url: string | undefined;
  const dashIdx = body.lastIndexOf(" \u2014 ");
  if (dashIdx >= 0) {
    main = body.slice(0, dashIdx).trim();
    url = body.slice(dashIdx + 3).trim();
  }
  if (!url) {
    const bareUrl = body.match(/https?:\/\/\S+$/);
    if (bareUrl && bareUrl.index !== undefined && bareUrl.index > 0) {
      main = body.slice(0, bareUrl.index).replace(/[—–\s]+$/, "").trim();
      url = bareUrl[0];
    }
  }

  // "Authors (Year), …" — authors are everything before the (YYYY).
  let authors = "";
  let year: string | undefined;
  let rest = main;
  const ym = main.match(/^(.*?)\s*\((\d{4}[a-z]?)\)\s*,?\s*(.*)$/);
  if (ym && ym[1].trim()) {
    authors = ym[1].trim();
    year = ym[2];
    rest = ym[3].trim();
  }

  // "Journal. Title." — the journal is the segment before the first ". "
  // separator (journal names may contain commas; titles follow).
  let journal: string | undefined;
  let title = rest;
  const jm = rest.match(/^(.+?)\.\s+(.+)$/);
  if (jm && jm[2].trim().length >= 10) {
    journal = jm[1].trim();
    title = jm[2].trim();
  }
  title = title.replace(/\.$/, "").trim();

  return { authors, year, journal, title: title || main, url };
}

/** Extract a PubMed PMID / DOI from a reference URL, if present. */
export function idsFromUrl(url?: string): { pmid?: string; doi?: string } {
  if (!url) return {};
  const pmid = url.match(/pubmed\.ncbi\.nlm\.nih\.gov\/(\d+)/)?.[1];
  const doi = url
    .match(/doi\.org\/(10\.\S+)/i)?.[1]
    ?.replace(/[.,;)\]]+$/, "");
  return { pmid, doi };
}

// ─────────────────────────────────────────────────────────────────────────────
// EndNote XML (the payload that gets base64-encoded into w:fldData)
// ─────────────────────────────────────────────────────────────────────────────

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

function el(tag: string, value?: string | null): string {
  return value ? `<${tag}>${escapeXml(value)}</${tag}>` : "";
}

/** Synthetic library id — EndNote matches records by db-id + RecNumber. */
function dbIdFor(rec: EndNoteRecord): string {
  return createHash("sha1")
    .update(rec.doi || rec.title || String(rec.n))
    .digest("hex")
    .slice(0, 32);
}

function recordXml(rec: EndNoteRecord): string {
  const parts: string[] = [];
  parts.push(`<rec-number>${rec.n}</rec-number>`);
  parts.push(`<foreign-keys><key app="EN" db-id="${dbIdFor(rec)}">${rec.n}</key></foreign-keys>`);
  // ref-type 17 = Journal Article (all SciWrite refs are journal articles)
  parts.push(`<ref-type name="Journal Article">17</ref-type>`);
  if (rec.authors.length > 0) {
    parts.push(
      `<contributors><authors>${rec.authors.map((a) => el("author", a)).join("")}</authors></contributors>`,
    );
  }
  parts.push(
    `<titles>${el("title", rec.title || `Reference ${rec.n}`)}${el("secondary-title", rec.journal)}</titles>`,
  );
  if (rec.journal) parts.push(`<periodical>${el("full-title", rec.journal)}</periodical>`);
  if (rec.year) parts.push(`<dates>${el("year", rec.year)}</dates>`);
  if (rec.doi) parts.push(el("electronic-resource-num", rec.doi));
  if (rec.pmid) parts.push(el("accession-num", `PMID:${rec.pmid}`));
  if (rec.url) parts.push(`<urls><related-urls>${el("url", rec.url)}</related-urls></urls>`);
  return `<record>${parts.join("")}</record>`;
}

/**
 * Build the EndNote XML payload for one citation group. A grouped citation
 * ("[1,2]") carries one <Cite> element per referenced record under a single
 * <EndNote> root, sharing the same DisplayText.
 */
export function buildEndnoteXml(display: string, records: EndNoteRecord[]): string {
  const cites = records
    .map((r) => {
      const head = [
        el("Author", r.authors[0]),
        el("Year", r.year),
        `<RecNum>${r.n}</RecNum>`,
        el("DisplayText", display),
      ].join("");
      return `<Cite>${head}${recordXml(r)}</Cite>`;
    })
    .join("");
  return `<EndNote>${cites}</EndNote>`;
}

/** Base64-encode the EndNote XML, wrapped at 76 chars/line (EndNote layout). */
export function encodeFldData(xml: string): string {
  const b64 = Buffer.from(xml, "utf-8").toString("base64");
  const lines: string[] = [];
  for (let i = 0; i < b64.length; i += 76) lines.push(b64.slice(i, i + 76));
  return lines.join("\n");
}

// ─────────────────────────────────────────────────────────────────────────────
// WordprocessingML field runs (raw XML injected into document.xml)
// ─────────────────────────────────────────────────────────────────────────────

/** Clone a run-properties string and ensure <w:noProof/> (field-control runs). */
function rprWithNoProof(rpr: string): string {
  if (!rpr) return "<w:rPr><w:noProof/></w:rPr>";
  if (rpr.includes("<w:noProof")) return rpr;
  return rpr.replace(/<\/w:rPr>$/, "<w:noProof/></w:rPr>");
}

function ctrlRun(rpr: string, inner: string): string {
  return `<w:r>${rprWithNoProof(rpr)}${inner}</w:r>`;
}

function fldCharRun(rpr: string, type: "begin" | "separate" | "end", fldData?: string): string {
  const data = fldData ? `<w:fldData xml:space="preserve">${fldData}</w:fldData>` : "";
  const dirty = type === "begin" ? ` w:dirty="true"` : "";
  return ctrlRun(rpr, `<w:fldChar w:fldCharType="${type}"${dirty}>${data}</w:fldChar>`);
}

function instrRun(rpr: string, instr: string): string {
  return ctrlRun(rpr, `<w:instrText xml:space="preserve">${escapeXml(instr)}</w:instrText>`);
}

/** A visible text run carrying the given (already serialized) rPr. */
function textRun(rpr: string, text: string): string {
  return `<w:r>${rpr}<w:t xml:space="preserve">${escapeXml(text)}</w:t></w:r>`;
}

/**
 * Compound ADDIN EN.CITE field wrapping the visible citation run. The nested
 * EN.CITE.DATA field (with the base64 record payload) lives entirely inside
 * the outer field's instruction section, exactly as EndNote writes it.
 */
function citationFieldXml(
  rpr: string,
  visibleRunXml: string,
  display: string,
  records: EndNoteRecord[],
): string {
  const data = encodeFldData(buildEndnoteXml(display, records));
  return [
    fldCharRun(rpr, "begin"),
    instrRun(rpr, " ADDIN EN.CITE "),
    fldCharRun(rpr, "begin", data),
    instrRun(rpr, " ADDIN EN.CITE.DATA "),
    fldCharRun(rpr, "end"),
    fldCharRun(rpr, "separate"),
    visibleRunXml,
    fldCharRun(rpr, "end"),
  ].join("");
}

/** Field-opening runs for the bibliography (ADDIN EN.REFLIST). */
function reflistOpenXml(rpr: string): string {
  return [
    fldCharRun(rpr, "begin"),
    instrRun(rpr, " ADDIN EN.REFLIST "),
    fldCharRun(rpr, "separate"),
  ].join("");
}

// ─────────────────────────────────────────────────────────────────────────────
// document.xml surgery
// ─────────────────────────────────────────────────────────────────────────────

/** One citation anchor: the placeholder token and the original [n] marker. */
export interface CitationOccurrence {
  token: string;
  marker: string;
  records: EndNoteRecord[];
}

interface RunSpan {
  start: number;
  end: number;
  rpr: string;
}

/**
 * Locate the <w:r>…</w:r> element containing `token` and extract its rPr.
 * Tokens are generated by buildDocx and unique, so the first hit is the hit.
 */
function findRun(xml: string, token: string): RunSpan | null {
  const idx = xml.indexOf(token);
  if (idx < 0) return null;
  const before = xml.slice(0, idx);
  const start = Math.max(before.lastIndexOf("<w:r>"), before.lastIndexOf("<w:r "));
  const end = xml.indexOf("</w:r>", idx);
  if (start < 0 || end < 0) return null;
  const runXml = xml.slice(start, end + "</w:r>".length);
  const m = runXml.match(/<w:rPr>[\s\S]*?<\/w:rPr>/);
  return { start, end: end + "</w:r>".length, rpr: m ? m[0] : "" };
}

/**
 * Inject EndNote CWYW fields into a packed document.xml:
 *  - every citation placeholder token is replaced by a compound EN.CITE field
 *    whose cached result is the original superscript marker text
 *  - the bibliography open/close tokens are replaced by the EN.REFLIST field
 *    wrapper, so the visible reference list becomes the field's result
 *
 * Occurrences whose records could not be resolved (orphan [n]) keep their
 * plain superscript text — no field, no data loss.
 */
export function injectEndnoteFields(
  xml: string,
  occurrences: CitationOccurrence[],
  openToken: string,
  closeToken: string,
): string {
  let out = xml;
  for (const occ of occurrences) {
    const run = findRun(out, occ.token);
    if (!run) continue;
    const visible = textRun(run.rpr, occ.marker);
    const replacement = occ.records.length > 0
      ? citationFieldXml(run.rpr, visible, occ.marker, occ.records)
      : visible;
    out = out.slice(0, run.start) + replacement + out.slice(run.end);
  }
  const open = findRun(out, openToken);
  if (open) {
    out = out.slice(0, open.start) + reflistOpenXml(open.rpr) + out.slice(open.end);
  }
  const close = findRun(out, closeToken);
  if (close) {
    out = out.slice(0, close.start) + fldCharRun(close.rpr, "end") + out.slice(close.end);
  }
  // Structural sanity: every field begin must have a matching end. Note that
  // the nested EN.CITE.DATA field intentionally has NO separator (it carries
  // no result — its payload is the base64 fldData inside the begin fldChar),
  // so separates are NOT expected to equal begins.
  const begins = (out.match(/w:fldCharType="begin"/g) || []).length;
  const ends = (out.match(/w:fldCharType="end"/g) || []).length;
  if (begins !== ends) {
    throw new Error(`EndNote field injection produced unbalanced fields (${begins} begin / ${ends} end)`);
  }
  return out;
}
